export const API_URL = 'http://localhost:4000/api/post'
export const API_URL_USER = 'http://localhost:4000/api/user'
export const API_URL_USER_LOGIN = 'http://localhost:4000/api/user/login'
export const API_URL_USER_SIGNUP = 'http://localhost:4000/api/user/signup'
export const API_URL_USER_DELETE = 'http://localhost:4000/api/user/delete-user'